resolver: lts-8.0
packages:
    - 'prettyprinter'
    - 'prettyprinter-ansi-terminal'
    - 'prettyprinter-compat-wl-pprint'
    - 'prettyprinter-compat-ansi-wl-pprint'
    - 'prettyprinter-compat-annotated-wl-pprint'
extra-deps: []
flags: {}
extra-package-dbs: []
