#define APPLICATIVE_MONAD    MIN_VERSION_base(4,8,0)
#define FOLDABLE_TRAVERSABLE MIN_VERSION_base(4,8,0)
#define MONOID_IN_PRELUDE    MIN_VERSION_base(4,8,0)
#define NATURAL_IN_BASE      MIN_VERSION_base(4,8,0)
#define SEMIGROUP_IN_BASE    MIN_VERSION_base(4,8,0)

#define MONAD_FAIL           MIN_VERSION_base(4,9,0)
