#!/usr/bin/env bash

# This script generates the Haddocks and uploads them to a remote repository. I
# use Github as a temporary host before release, pushing this to
# quchen/ansi-wl-pprint-docdump.

set -euo pipefail

cd "$(stack path --project-root)"
stack haddock
cd "$(stack path --local-doc-root)"
git init
if ! (git remote | grep haddockdump > /dev/null); then
    ORIGIN="git@github.com:quchen/ansi-wl-pprint-docdump.git"
    echo "haddockdump not found! Adding remote haddockdump $ORIGIN"
    git remote add haddockdump "$ORIGIN"
    git fetch --all
    git checkout --track haddockdump/master --force
fi
git add .
git commit -am "Update docdump [$(date -I)]" --quiet
git push
