#!/usr/bin/env bash

# This script generates the Haddocks and uploads them to a remote repository. I
# use Github as a temporary host before release, pushing this to
# quchen/ansi-wl-pprint-docdump.

set -euo pipefail

cd "$(stack path --project-root)"
stack haddock
cd "$(stack path --local-doc-root)"
if ! (git remote | grep origin > /dev/null); then
    ORIGIN="git@github.com:quchen/ansi-wl-pprint-docdump.git"
    echo "origin not found! Adding remote origin $ORIGIN"
    git remote add origin "$ORIGIN"
fi
git add .
git commit --amend --no-edit
git push --force
