#!/usr/bin/env bash

set -euo pipefail

cd "$(stack path --project-root)"
./scripts/generate_readme

cd "$(git rev-parse --show-toplevel)"
set +e
git diff --exit-code -U0 --word-diff README.md
EXIT=$?
set -e

if [[ $EXIT -ne 0 ]]; then
    echo "The generated README differs from the tracked one!"
    echo "Please regenerate it by running ./scripts/generate_readme."
fi
exit $EXIT
