#!/usr/bin/env bash

set -euo pipefail

stylish-haskell --version

cd "$(stack path --project-root)"
git stash
find prettyprinter* -name "*.hs" -exec stylish-haskell --inplace {} \;

cd "$(git rev-parse --show-toplevel)"
set +e
git diff --exit-code -U0
EXIT=$?
set -e

if [[ $EXIT -ne 0 ]]; then
    echo '╭────────────────────────────────────────────────────────────────────────╮'
    echo '│ Stylish-Haskell introduced changes.                                    │'
    echo '│ Please run it before committing!                                       │'
    echo '│                                                                        │'
    echo '│ find prettyprinter* -name "*.hs" -exec stylish-haskell --inplace {} \; │'
    echo '╰────────────────────────────────────────────────────────────────────────╯'
fi
exit $EXIT
